### PR TITLE
Improvements for adding events

### PR DESCRIPTION
**Pull request by choefele**
*Issue #, if available:*
No existing issue

*Description of changes:*
This PR improves the code for creating new events. The main enhancement is a fix to avoid accessing UI APIs on a background thread when adding an event, which triggered the main thread checker.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mburns-acom** [comment]
Thanks. These changes helped me.

**Review by rohandubal — COMMENTED** [review]
Thanks for the PR! The changes look good! 

Could you please rebase with the latest commit so that we can accept and merge? Thanks again!

**Comment by choefele** [comment]
I rebased the commits, but let me quickly check that I merged correctly. Will update this PR when I'm done

**Comment by choefele** [comment]
All good – ready for merging @rohandubal

**Review by rohandubal — APPROVED** [review]

**Pull request merged**
